main_loop_freq: 30
unity_render: yes
scene_id: 4                             # 0 wasteland, 1 japanese street, 4 empty forest in standalone (SR)
odom_topic: /drone0/mavros/local_position/odom  # Topic of UAV odometry for render
quad_size: 0.1
#ply_path: "/flightrender/RPG_Flightmare/pointcloud_data/"  # temporary path of saving point could (for visualization)
ply_path: "/home/zzw/YOPO/run/yopo_gazebo/"  # temporary path of saving point could (for visualization)

rgb_camera_left:
  on: yes 
  t_BC: [0.0, 0.0, 0.1]   # translational vector of the camera with respect to the body frame
  r_BC: [0.0, 0.0, -90]  # rotational angle (roll, pitch, yaw) of the camera in degree
  width: 640
  height: 480
  fov: 90.0               # Horizontal FOV
  enable_depth: yes
  enable_segmentation: no
  enable_opticalflow: no

# enable stereo depth when rgb_camera_right on (If used, please use larger resolution (e.g., 640x360))
rgb_camera_right:
  on: no
  t_BC: [0.0, -0.2, 0.1]  # translational vector of the camera with repect to the body frame
  r_BC: [0.0, 0.0, -90]  # rotational angle (roll, pitch, yaw) of the camera in degree

unity:
  spawn_trees: true
  save_pointcloud: true               # set to 'false' to save startup time, if visualization is not needed.
  avg_tree_spacing: 4.0               # average spacing between trees
  bounding_box: [80.0, 80.0, 11.0]    # spawn objects within this bounding box
  bounding_box_origin: [-10, 20, 2.5]
  pointcloud_resolution: 0.2