env:
  seed: 1
  scene_id: 4     # 0 wasteland, 1 japanese street, 4 emptyforest in SR standalone
  num_envs: 128    # Important: same to batch size!
  num_threads: 32
  dataset_path: "/run/yopo_gazebo/"  # path of training dataset
  ply_path: "/run/yopo_gazebo/"      # path of the point could of training data

unity:
  spawn_trees: true
  avg_tree_spacing: 4                 # average spacing between trees
  # larger than the position to generate the drone to ensure the completeness of the point cloud in edge.
  bounding_box: [80.0, 80.0, 11]      # spawn objects within this bounding box
  bounding_box_origin: [-10, 20, 2.5]
  pointcloud_resolution: 0.2
